// This file is automatically generated. Do not edit.
package net.socialgamer.cah.handlers;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;


public class Handlers {
  public static final Map<String, Class<? extends Handler>> LIST;

  static {
    final Map<String, Class<? extends Handler>> list = new HashMap<String, Class<? extends Handler>>();
    list.put(AddCardsetHandler.OP, AddCardsetHandler.class);
    list.put(BanHandler.OP, BanHandler.class);
    list.put(ChangeGameOptionHandler.OP, ChangeGameOptionHandler.class);
    list.put(ChatHandler.OP, ChatHandler.class);
    list.put(CreateGameHandler.OP, CreateGameHandler.class);
    list.put(FirstLoadHandler.OP, FirstLoadHandler.class);
    list.put(GameChatHandler.OP, GameChatHandler.class);
    list.put(GameHostHandler.OP, GameHostHandler.class);
    list.put(GameListHandler.OP, GameListHandler.class);
    list.put(GameSkipHandler.OP, GameSkipHandler.class);
    list.put(GetCardsHandler.OP, GetCardsHandler.class);
    list.put(GetGameInfoHandler.OP, GetGameInfoHandler.class);
    list.put(JoinGameHandler.OP, JoinGameHandler.class);
    list.put(JudgeSelectHandler.OP, JudgeSelectHandler.class);
    list.put(KickHandler.OP, KickHandler.class);
    list.put(LeaveGameHandler.OP, LeaveGameHandler.class);
    list.put(ListCardsetsHandler.OP, ListCardsetsHandler.class);
    list.put(LogoutHandler.OP, LogoutHandler.class);
    list.put(NamesHandler.OP, NamesHandler.class);
    list.put(PlayCardHandler.OP, PlayCardHandler.class);
    list.put(RegisterHandler.OP, RegisterHandler.class);
    list.put(RemoveCardsetHandler.OP, RemoveCardsetHandler.class);
    list.put(ScoreHandler.OP, ScoreHandler.class);
    list.put(SpectateGameHandler.OP, SpectateGameHandler.class);
    list.put(StartGameHandler.OP, StartGameHandler.class);
    list.put(StopGameHandler.OP, StopGameHandler.class);
    list.put(WhoisHandler.OP, WhoisHandler.class);
    LIST = Collections.unmodifiableMap(list);
  }

  private Handlers() {
  }
}
